Update git-reviews

diff --git a/scripts/bin/git-reviews b/scripts/bin/git-reviews
--- a/scripts/bin/git-reviews
+++ b/scripts/bin/git-reviews
@@ -1,31 +1,42 @@
 #!/bin/bash
 
 if ! [ -x "$(command -v glab)" ]; then
-  echo "glab cli is not installed"
+  echo "ERROR: Gitlab Cli is not installed"
   return
 fi
 
-git pull
-ASSIGNEES=$(glab mr list --assignee hcramer1 | cat | grep -v 'No open merge' | tail -n3 | awk '{print $NF}' | tr -d '()' | awk NF)
-REVIEWERS=$(glab mr list --reviewer hcramer1 | cat | grep -v 'No open merge' | tail -n3 | awk '{print $NF}' | tr -d '()' | awk NF)
+LOGGED_IN=$(glab auth status 2>&1)
 
-if [[ $ASSIGNEES == "" && $REVIEWERS == "" ]]; then
-  exit
+if [ $? -ne 0 ]; then
+  echo "Error: Not logged into Gitlab CLI"
+  exit 1
 fi
 
-combined_values=($ASSIGNEES $REVIEWERS)
-uniq=($(printf "%s\n" "${combined_values[@]}" | sort -u));
+USER=$(echo "$LOGGED_IN" | awk '{ print $7 }' | head -2 | tail -1)
 
-MR=$(for value in "${uniq[@]}"; do
-  author=$(git log --format="%an" -n 1 $value)
-  echo "$value ($author)"
-done | fzf --prompt "Choose Your MR: " --height=~50% --layout=reverse --border --exit-0)
-
-if [[ -z $MR ]]; then
-  exit
+if [[ -z $USER ]]; then
+  echo "Error: Gitlab user could not be detected"
+  exit 1
 fi
 
-branch_name=$(echo $MR | awk '{print $1}')
+git pull --quiet
 
-git checkout -q $branch_name
-git pull
+ASSIGNEES=$(glab mr list --assignee "$USER" | cat | grep '(main)')
+REVIEWERS=$(glab mr list --reviewer "$USER" | cat | grep '(main)')
+ALL=$(paste -d'\n' <(echo "$ASSIGNEES") <(echo "$REVIEWERS") | sort -u | awk NF)
+
+if [[ -z $ALL ]]; then
+  echo "Error: You are not an assignee or reviewer for anything in this repository"
+  exit 1
+fi
+
+CHOICE=$(echo "$ALL" | fzf --prompt "Choose Your MR: " --height=~50% --layout=reverse --border --exit-0)
+
+if [[ -z $CHOICE ]]; then
+  exit 0
+fi
+
+MR=$(echo "$CHOICE" | awk '{ print $NF }' | tr -d '()')
+
+git checkout --quiet "$MR"
+git pull --quiet
